#!/usr/bin/env sh

invoke(){
  echo "We're about to add ${key_name} to our list of accepted keys."
  echo "What that means is that you have good reason to believe that this key really is controlled by the person"
  echo "that it says that it is."
  echo "You'll be asked twice if you really want to do this, because it's an important step."
  echo "Picture the owner of the key looking you in the eyes and saying 'Do you trust me?'"
  echo
  echo "After the first time you confirm that you want to sign the key, you'll be shown "
  echo "the 'Primary key fingerprint' of the key. You need to check that against the key fingerprint"
  echo "that the key's owner gives you."
  echo "(If they're using simplekey too, they can run `simplekey fingerprint` to list it."
  echo

  $GPG --sign-key $key_name
  $GPG --edit-key $key_name <<-COMMAND
        trust
        3
        save
COMMAND

  $GPG --send-keys $key_name
}
